### ISSUE TITLE
Identidade Visual - Logo

### ISSUE THREAD

**Issue by thauska** [vuejs-norte/adopetz#1]

**Comment by mandyellow** [comment]
Olá! Fiz uma opção de logo para o seu projeto! Veja se gostam de depois me avisem para fazer ajustes ou subir uma PR com os formatos que vocês precisam, geralmente mando PNG e SVG. 🦊 

Coloquei uma versão vertical e uma horizontal, e também abaixo uma aplicação negativada em fundo escuro.

![image](https://user-images.githubusercontent.com/30158643/94933699-214ef300-04a1-11eb-91e6-e3debda13554.png)

**Comment by biancassilva** [comment]
Aprovadíssimo!

**Comment by mandyellow** [comment]
Posso criar uma pasta 'media' ou 'images' e colocar o logo lá? Eu geralmente coloco em PNG e SVG, se quiserem outros formatos, me avisem também 🦊

**Comment by thauska** [comment]
@mandyellow na raiz do projeto, pode incluir as imagens PNG e SVG nessa pasta com nome artworks. Muito grata! 

https://github.com/vuejs-norte/adopetz/tree/master/artworks
